name: s_metar
description: Parse/decode METAR/TAF aeronautical weather reports (wind, visibility, weather, clouds...). Fetch live/past METAR/TAF data from aviationweather.gov API.


license: MIT

issue_tracker: https://github.com/SoundSliced/s_metar/issues
repository: https://github.com/SoundSliced/s_metar
version: 2.1.0
homepage: https://github.com/SoundSliced/s_metar

topics:
  - aviation
  - weather
  - metar
  - taf
  - meteorology

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  s_packages: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
